/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as MainTeamRouteImport } from './routes/_main/team'
import { Route as MainSecretsRouteImport } from './routes/_main/secrets'
import { Route as MainDomainsRouteImport } from './routes/_main/domains'
import { Route as MainActivityRouteImport } from './routes/_main/activity'
import { Route as MainVolumesIndexRouteImport } from './routes/_main/volumes/index'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainServicesIndexRouteImport } from './routes/_main/services/index'
import { Route as MainVolumesSnapshotsRouteImport } from './routes/_main/volumes/snapshots'
import { Route as MainSettingsRegistryConfigurationRouteImport } from './routes/_main/settings/registry-configuration'
import { Route as MainSettingsPlansRouteImport } from './routes/_main/settings/plans'
import { Route as MainSettingsBillingRouteImport } from './routes/_main/settings/billing'
import { Route as MainSettingsApiRouteImport } from './routes/_main/settings/api'
import { Route as MainServicesNewRouteImport } from './routes/_main/services/new'
import { Route as MainServicesDeployRouteImport } from './routes/_main/services/deploy'
import { Route as MainDatabaseServicesNewRouteImport } from './routes/_main/database-services/new'
import { Route as MainServicesServiceIdRouteRouteImport } from './routes/_main/services/$serviceId/route'
import { Route as MainUserSettingsIndexRouteImport } from './routes/_main/user.settings/index'
import { Route as MainServicesServiceIdIndexRouteImport } from './routes/_main/services/$serviceId/index'
import { Route as MainDatabaseServicesServiceIdIndexRouteImport } from './routes/_main/database-services/$serviceId/index'
import { Route as MainUserSettingsOrganizationsRouteImport } from './routes/_main/user.settings/organizations'
import { Route as MainUserSettingsApiRouteImport } from './routes/_main/user.settings/api'
import { Route as MainServicesServiceIdSettingsRouteImport } from './routes/_main/services/$serviceId/settings'
import { Route as MainServicesServiceIdMetricsRouteImport } from './routes/_main/services/$serviceId/metrics'
import { Route as MainServicesServiceIdConsoleRouteImport } from './routes/_main/services/$serviceId/console'
import { Route as MainDatabaseServicesServiceIdSettingsRouteImport } from './routes/_main/database-services/$serviceId/settings'
import { Route as MainDatabaseServicesServiceIdRolesRouteImport } from './routes/_main/database-services/$serviceId/roles'
import { Route as MainDatabaseServicesServiceIdDatabasesRouteImport } from './routes/_main/database-services/$serviceId/databases'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainTeamRoute = MainTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSecretsRoute = MainSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDomainsRoute = MainDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainActivityRoute = MainActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainVolumesIndexRoute = MainVolumesIndexRouteImport.update({
  id: '/volumes/',
  path: '/volumes/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainServicesIndexRoute = MainServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainVolumesSnapshotsRoute = MainVolumesSnapshotsRouteImport.update({
  id: '/volumes/snapshots',
  path: '/volumes/snapshots',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRegistryConfigurationRoute =
  MainSettingsRegistryConfigurationRouteImport.update({
    id: '/settings/registry-configuration',
    path: '/settings/registry-configuration',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainSettingsPlansRoute = MainSettingsPlansRouteImport.update({
  id: '/settings/plans',
  path: '/settings/plans',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsBillingRoute = MainSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsApiRoute = MainSettingsApiRouteImport.update({
  id: '/settings/api',
  path: '/settings/api',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainServicesNewRoute = MainServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainServicesDeployRoute = MainServicesDeployRouteImport.update({
  id: '/services/deploy',
  path: '/services/deploy',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDatabaseServicesNewRoute = MainDatabaseServicesNewRouteImport.update({
  id: '/database-services/new',
  path: '/database-services/new',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainServicesServiceIdRouteRoute =
  MainServicesServiceIdRouteRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainUserSettingsIndexRoute = MainUserSettingsIndexRouteImport.update({
  id: '/user/settings/',
  path: '/user/settings/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainServicesServiceIdIndexRoute =
  MainServicesServiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainServicesServiceIdRouteRoute,
  } as any)
const MainDatabaseServicesServiceIdIndexRoute =
  MainDatabaseServicesServiceIdIndexRouteImport.update({
    id: '/database-services/$serviceId/',
    path: '/database-services/$serviceId/',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainUserSettingsOrganizationsRoute =
  MainUserSettingsOrganizationsRouteImport.update({
    id: '/user/settings/organizations',
    path: '/user/settings/organizations',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainUserSettingsApiRoute = MainUserSettingsApiRouteImport.update({
  id: '/user/settings/api',
  path: '/user/settings/api',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainServicesServiceIdSettingsRoute =
  MainServicesServiceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MainServicesServiceIdRouteRoute,
  } as any)
const MainServicesServiceIdMetricsRoute =
  MainServicesServiceIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => MainServicesServiceIdRouteRoute,
  } as any)
const MainServicesServiceIdConsoleRoute =
  MainServicesServiceIdConsoleRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => MainServicesServiceIdRouteRoute,
  } as any)
const MainDatabaseServicesServiceIdSettingsRoute =
  MainDatabaseServicesServiceIdSettingsRouteImport.update({
    id: '/database-services/$serviceId/settings',
    path: '/database-services/$serviceId/settings',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainDatabaseServicesServiceIdRolesRoute =
  MainDatabaseServicesServiceIdRolesRouteImport.update({
    id: '/database-services/$serviceId/roles',
    path: '/database-services/$serviceId/roles',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainDatabaseServicesServiceIdDatabasesRoute =
  MainDatabaseServicesServiceIdDatabasesRouteImport.update({
    id: '/database-services/$serviceId/databases',
    path: '/database-services/$serviceId/databases',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/activity': typeof MainActivityRoute
  '/domains': typeof MainDomainsRoute
  '/secrets': typeof MainSecretsRoute
  '/team': typeof MainTeamRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof MainIndexRoute
  '/services/$serviceId': typeof MainServicesServiceIdRouteRouteWithChildren
  '/database-services/new': typeof MainDatabaseServicesNewRoute
  '/services/deploy': typeof MainServicesDeployRoute
  '/services/new': typeof MainServicesNewRoute
  '/settings/api': typeof MainSettingsApiRoute
  '/settings/billing': typeof MainSettingsBillingRoute
  '/settings/plans': typeof MainSettingsPlansRoute
  '/settings/registry-configuration': typeof MainSettingsRegistryConfigurationRoute
  '/volumes/snapshots': typeof MainVolumesSnapshotsRoute
  '/services': typeof MainServicesIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/volumes': typeof MainVolumesIndexRoute
  '/database-services/$serviceId/databases': typeof MainDatabaseServicesServiceIdDatabasesRoute
  '/database-services/$serviceId/roles': typeof MainDatabaseServicesServiceIdRolesRoute
  '/database-services/$serviceId/settings': typeof MainDatabaseServicesServiceIdSettingsRoute
  '/services/$serviceId/console': typeof MainServicesServiceIdConsoleRoute
  '/services/$serviceId/metrics': typeof MainServicesServiceIdMetricsRoute
  '/services/$serviceId/settings': typeof MainServicesServiceIdSettingsRoute
  '/user/settings/api': typeof MainUserSettingsApiRoute
  '/user/settings/organizations': typeof MainUserSettingsOrganizationsRoute
  '/database-services/$serviceId': typeof MainDatabaseServicesServiceIdIndexRoute
  '/services/$serviceId/': typeof MainServicesServiceIdIndexRoute
  '/user/settings': typeof MainUserSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/activity': typeof MainActivityRoute
  '/domains': typeof MainDomainsRoute
  '/secrets': typeof MainSecretsRoute
  '/team': typeof MainTeamRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof MainIndexRoute
  '/database-services/new': typeof MainDatabaseServicesNewRoute
  '/services/deploy': typeof MainServicesDeployRoute
  '/services/new': typeof MainServicesNewRoute
  '/settings/api': typeof MainSettingsApiRoute
  '/settings/billing': typeof MainSettingsBillingRoute
  '/settings/plans': typeof MainSettingsPlansRoute
  '/settings/registry-configuration': typeof MainSettingsRegistryConfigurationRoute
  '/volumes/snapshots': typeof MainVolumesSnapshotsRoute
  '/services': typeof MainServicesIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/volumes': typeof MainVolumesIndexRoute
  '/database-services/$serviceId/databases': typeof MainDatabaseServicesServiceIdDatabasesRoute
  '/database-services/$serviceId/roles': typeof MainDatabaseServicesServiceIdRolesRoute
  '/database-services/$serviceId/settings': typeof MainDatabaseServicesServiceIdSettingsRoute
  '/services/$serviceId/console': typeof MainServicesServiceIdConsoleRoute
  '/services/$serviceId/metrics': typeof MainServicesServiceIdMetricsRoute
  '/services/$serviceId/settings': typeof MainServicesServiceIdSettingsRoute
  '/user/settings/api': typeof MainUserSettingsApiRoute
  '/user/settings/organizations': typeof MainUserSettingsOrganizationsRoute
  '/database-services/$serviceId': typeof MainDatabaseServicesServiceIdIndexRoute
  '/services/$serviceId': typeof MainServicesServiceIdIndexRoute
  '/user/settings': typeof MainUserSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_main/activity': typeof MainActivityRoute
  '/_main/domains': typeof MainDomainsRoute
  '/_main/secrets': typeof MainSecretsRoute
  '/_main/team': typeof MainTeamRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_main/': typeof MainIndexRoute
  '/_main/services/$serviceId': typeof MainServicesServiceIdRouteRouteWithChildren
  '/_main/database-services/new': typeof MainDatabaseServicesNewRoute
  '/_main/services/deploy': typeof MainServicesDeployRoute
  '/_main/services/new': typeof MainServicesNewRoute
  '/_main/settings/api': typeof MainSettingsApiRoute
  '/_main/settings/billing': typeof MainSettingsBillingRoute
  '/_main/settings/plans': typeof MainSettingsPlansRoute
  '/_main/settings/registry-configuration': typeof MainSettingsRegistryConfigurationRoute
  '/_main/volumes/snapshots': typeof MainVolumesSnapshotsRoute
  '/_main/services/': typeof MainServicesIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/_main/volumes/': typeof MainVolumesIndexRoute
  '/_main/database-services/$serviceId/databases': typeof MainDatabaseServicesServiceIdDatabasesRoute
  '/_main/database-services/$serviceId/roles': typeof MainDatabaseServicesServiceIdRolesRoute
  '/_main/database-services/$serviceId/settings': typeof MainDatabaseServicesServiceIdSettingsRoute
  '/_main/services/$serviceId/console': typeof MainServicesServiceIdConsoleRoute
  '/_main/services/$serviceId/metrics': typeof MainServicesServiceIdMetricsRoute
  '/_main/services/$serviceId/settings': typeof MainServicesServiceIdSettingsRoute
  '/_main/user/settings/api': typeof MainUserSettingsApiRoute
  '/_main/user/settings/organizations': typeof MainUserSettingsOrganizationsRoute
  '/_main/database-services/$serviceId/': typeof MainDatabaseServicesServiceIdIndexRoute
  '/_main/services/$serviceId/': typeof MainServicesServiceIdIndexRoute
  '/_main/user/settings/': typeof MainUserSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/activity'
    | '/domains'
    | '/secrets'
    | '/team'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/services/$serviceId'
    | '/database-services/new'
    | '/services/deploy'
    | '/services/new'
    | '/settings/api'
    | '/settings/billing'
    | '/settings/plans'
    | '/settings/registry-configuration'
    | '/volumes/snapshots'
    | '/services'
    | '/settings'
    | '/volumes'
    | '/database-services/$serviceId/databases'
    | '/database-services/$serviceId/roles'
    | '/database-services/$serviceId/settings'
    | '/services/$serviceId/console'
    | '/services/$serviceId/metrics'
    | '/services/$serviceId/settings'
    | '/user/settings/api'
    | '/user/settings/organizations'
    | '/database-services/$serviceId'
    | '/services/$serviceId/'
    | '/user/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/activity'
    | '/domains'
    | '/secrets'
    | '/team'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/database-services/new'
    | '/services/deploy'
    | '/services/new'
    | '/settings/api'
    | '/settings/billing'
    | '/settings/plans'
    | '/settings/registry-configuration'
    | '/volumes/snapshots'
    | '/services'
    | '/settings'
    | '/volumes'
    | '/database-services/$serviceId/databases'
    | '/database-services/$serviceId/roles'
    | '/database-services/$serviceId/settings'
    | '/services/$serviceId/console'
    | '/services/$serviceId/metrics'
    | '/services/$serviceId/settings'
    | '/user/settings/api'
    | '/user/settings/organizations'
    | '/database-services/$serviceId'
    | '/services/$serviceId'
    | '/user/settings'
  id:
    | '__root__'
    | '/_main'
    | '/auth'
    | '/_main/activity'
    | '/_main/domains'
    | '/_main/secrets'
    | '/_main/team'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/_main/'
    | '/_main/services/$serviceId'
    | '/_main/database-services/new'
    | '/_main/services/deploy'
    | '/_main/services/new'
    | '/_main/settings/api'
    | '/_main/settings/billing'
    | '/_main/settings/plans'
    | '/_main/settings/registry-configuration'
    | '/_main/volumes/snapshots'
    | '/_main/services/'
    | '/_main/settings/'
    | '/_main/volumes/'
    | '/_main/database-services/$serviceId/databases'
    | '/_main/database-services/$serviceId/roles'
    | '/_main/database-services/$serviceId/settings'
    | '/_main/services/$serviceId/console'
    | '/_main/services/$serviceId/metrics'
    | '/_main/services/$serviceId/settings'
    | '/_main/user/settings/api'
    | '/_main/user/settings/organizations'
    | '/_main/database-services/$serviceId/'
    | '/_main/services/$serviceId/'
    | '/_main/user/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/team': {
      id: '/_main/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof MainTeamRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/secrets': {
      id: '/_main/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof MainSecretsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/domains': {
      id: '/_main/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof MainDomainsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/activity': {
      id: '/_main/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof MainActivityRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/volumes/': {
      id: '/_main/volumes/'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof MainVolumesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/services/': {
      id: '/_main/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MainServicesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/volumes/snapshots': {
      id: '/_main/volumes/snapshots'
      path: '/volumes/snapshots'
      fullPath: '/volumes/snapshots'
      preLoaderRoute: typeof MainVolumesSnapshotsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/registry-configuration': {
      id: '/_main/settings/registry-configuration'
      path: '/settings/registry-configuration'
      fullPath: '/settings/registry-configuration'
      preLoaderRoute: typeof MainSettingsRegistryConfigurationRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/plans': {
      id: '/_main/settings/plans'
      path: '/settings/plans'
      fullPath: '/settings/plans'
      preLoaderRoute: typeof MainSettingsPlansRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/billing': {
      id: '/_main/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof MainSettingsBillingRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings/api': {
      id: '/_main/settings/api'
      path: '/settings/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof MainSettingsApiRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/services/new': {
      id: '/_main/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof MainServicesNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/services/deploy': {
      id: '/_main/services/deploy'
      path: '/services/deploy'
      fullPath: '/services/deploy'
      preLoaderRoute: typeof MainServicesDeployRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/database-services/new': {
      id: '/_main/database-services/new'
      path: '/database-services/new'
      fullPath: '/database-services/new'
      preLoaderRoute: typeof MainDatabaseServicesNewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/services/$serviceId': {
      id: '/_main/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof MainServicesServiceIdRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/user/settings/': {
      id: '/_main/user/settings/'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof MainUserSettingsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/services/$serviceId/': {
      id: '/_main/services/$serviceId/'
      path: '/'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof MainServicesServiceIdIndexRouteImport
      parentRoute: typeof MainServicesServiceIdRouteRoute
    }
    '/_main/database-services/$serviceId/': {
      id: '/_main/database-services/$serviceId/'
      path: '/database-services/$serviceId'
      fullPath: '/database-services/$serviceId'
      preLoaderRoute: typeof MainDatabaseServicesServiceIdIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/user/settings/organizations': {
      id: '/_main/user/settings/organizations'
      path: '/user/settings/organizations'
      fullPath: '/user/settings/organizations'
      preLoaderRoute: typeof MainUserSettingsOrganizationsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/user/settings/api': {
      id: '/_main/user/settings/api'
      path: '/user/settings/api'
      fullPath: '/user/settings/api'
      preLoaderRoute: typeof MainUserSettingsApiRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/services/$serviceId/settings': {
      id: '/_main/services/$serviceId/settings'
      path: '/settings'
      fullPath: '/services/$serviceId/settings'
      preLoaderRoute: typeof MainServicesServiceIdSettingsRouteImport
      parentRoute: typeof MainServicesServiceIdRouteRoute
    }
    '/_main/services/$serviceId/metrics': {
      id: '/_main/services/$serviceId/metrics'
      path: '/metrics'
      fullPath: '/services/$serviceId/metrics'
      preLoaderRoute: typeof MainServicesServiceIdMetricsRouteImport
      parentRoute: typeof MainServicesServiceIdRouteRoute
    }
    '/_main/services/$serviceId/console': {
      id: '/_main/services/$serviceId/console'
      path: '/console'
      fullPath: '/services/$serviceId/console'
      preLoaderRoute: typeof MainServicesServiceIdConsoleRouteImport
      parentRoute: typeof MainServicesServiceIdRouteRoute
    }
    '/_main/database-services/$serviceId/settings': {
      id: '/_main/database-services/$serviceId/settings'
      path: '/database-services/$serviceId/settings'
      fullPath: '/database-services/$serviceId/settings'
      preLoaderRoute: typeof MainDatabaseServicesServiceIdSettingsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/database-services/$serviceId/roles': {
      id: '/_main/database-services/$serviceId/roles'
      path: '/database-services/$serviceId/roles'
      fullPath: '/database-services/$serviceId/roles'
      preLoaderRoute: typeof MainDatabaseServicesServiceIdRolesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/database-services/$serviceId/databases': {
      id: '/_main/database-services/$serviceId/databases'
      path: '/database-services/$serviceId/databases'
      fullPath: '/database-services/$serviceId/databases'
      preLoaderRoute: typeof MainDatabaseServicesServiceIdDatabasesRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainServicesServiceIdRouteRouteChildren {
  MainServicesServiceIdConsoleRoute: typeof MainServicesServiceIdConsoleRoute
  MainServicesServiceIdMetricsRoute: typeof MainServicesServiceIdMetricsRoute
  MainServicesServiceIdSettingsRoute: typeof MainServicesServiceIdSettingsRoute
  MainServicesServiceIdIndexRoute: typeof MainServicesServiceIdIndexRoute
}

const MainServicesServiceIdRouteRouteChildren: MainServicesServiceIdRouteRouteChildren =
  {
    MainServicesServiceIdConsoleRoute: MainServicesServiceIdConsoleRoute,
    MainServicesServiceIdMetricsRoute: MainServicesServiceIdMetricsRoute,
    MainServicesServiceIdSettingsRoute: MainServicesServiceIdSettingsRoute,
    MainServicesServiceIdIndexRoute: MainServicesServiceIdIndexRoute,
  }

const MainServicesServiceIdRouteRouteWithChildren =
  MainServicesServiceIdRouteRoute._addFileChildren(
    MainServicesServiceIdRouteRouteChildren,
  )

interface MainRouteRouteChildren {
  MainActivityRoute: typeof MainActivityRoute
  MainDomainsRoute: typeof MainDomainsRoute
  MainSecretsRoute: typeof MainSecretsRoute
  MainTeamRoute: typeof MainTeamRoute
  MainIndexRoute: typeof MainIndexRoute
  MainServicesServiceIdRouteRoute: typeof MainServicesServiceIdRouteRouteWithChildren
  MainDatabaseServicesNewRoute: typeof MainDatabaseServicesNewRoute
  MainServicesDeployRoute: typeof MainServicesDeployRoute
  MainServicesNewRoute: typeof MainServicesNewRoute
  MainSettingsApiRoute: typeof MainSettingsApiRoute
  MainSettingsBillingRoute: typeof MainSettingsBillingRoute
  MainSettingsPlansRoute: typeof MainSettingsPlansRoute
  MainSettingsRegistryConfigurationRoute: typeof MainSettingsRegistryConfigurationRoute
  MainVolumesSnapshotsRoute: typeof MainVolumesSnapshotsRoute
  MainServicesIndexRoute: typeof MainServicesIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
  MainVolumesIndexRoute: typeof MainVolumesIndexRoute
  MainDatabaseServicesServiceIdDatabasesRoute: typeof MainDatabaseServicesServiceIdDatabasesRoute
  MainDatabaseServicesServiceIdRolesRoute: typeof MainDatabaseServicesServiceIdRolesRoute
  MainDatabaseServicesServiceIdSettingsRoute: typeof MainDatabaseServicesServiceIdSettingsRoute
  MainUserSettingsApiRoute: typeof MainUserSettingsApiRoute
  MainUserSettingsOrganizationsRoute: typeof MainUserSettingsOrganizationsRoute
  MainDatabaseServicesServiceIdIndexRoute: typeof MainDatabaseServicesServiceIdIndexRoute
  MainUserSettingsIndexRoute: typeof MainUserSettingsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainActivityRoute: MainActivityRoute,
  MainDomainsRoute: MainDomainsRoute,
  MainSecretsRoute: MainSecretsRoute,
  MainTeamRoute: MainTeamRoute,
  MainIndexRoute: MainIndexRoute,
  MainServicesServiceIdRouteRoute: MainServicesServiceIdRouteRouteWithChildren,
  MainDatabaseServicesNewRoute: MainDatabaseServicesNewRoute,
  MainServicesDeployRoute: MainServicesDeployRoute,
  MainServicesNewRoute: MainServicesNewRoute,
  MainSettingsApiRoute: MainSettingsApiRoute,
  MainSettingsBillingRoute: MainSettingsBillingRoute,
  MainSettingsPlansRoute: MainSettingsPlansRoute,
  MainSettingsRegistryConfigurationRoute:
    MainSettingsRegistryConfigurationRoute,
  MainVolumesSnapshotsRoute: MainVolumesSnapshotsRoute,
  MainServicesIndexRoute: MainServicesIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
  MainVolumesIndexRoute: MainVolumesIndexRoute,
  MainDatabaseServicesServiceIdDatabasesRoute:
    MainDatabaseServicesServiceIdDatabasesRoute,
  MainDatabaseServicesServiceIdRolesRoute:
    MainDatabaseServicesServiceIdRolesRoute,
  MainDatabaseServicesServiceIdSettingsRoute:
    MainDatabaseServicesServiceIdSettingsRoute,
  MainUserSettingsApiRoute: MainUserSettingsApiRoute,
  MainUserSettingsOrganizationsRoute: MainUserSettingsOrganizationsRoute,
  MainDatabaseServicesServiceIdIndexRoute:
    MainDatabaseServicesServiceIdIndexRoute,
  MainUserSettingsIndexRoute: MainUserSettingsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
