name: Build docker image

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - staging

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  DOCKER_IMAGE: eu.gcr.io/${{ secrets.GCP_PROJECT }}/koyeb-console
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  build-push:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure docker registry
        run: |
          echo "$GCP_CREDENTIALS" | base64 -d > "$HOME/gcp-key.json"

          gcloud auth activate-service-account --key-file "$HOME/gcp-key.json"
          gcloud --quiet config set project "$PROJECT_ID"

          gcloud auth configure-docker

      - name: Build docker image
        run: |
          docker build --rm=false \
            --build-arg ENVIRONMENT \
            --build-arg APP_VERSION \
            --build-arg API_URL \
            --build-arg WEBSITE_URL \
            --build-arg PAGE_CONTEXT_BASE_URL \
            --build-arg RECAPTCHA_CLIENT_KEY \
            --build-arg POSTHOG_API_HOST \
            --build-arg POSTHOG_KEY \
            --build-arg STRIPE_PUBLIC_KEY \
            --build-arg MAPBOX_TOKEN \
            --build-arg INTERCOM_APP_ID \
            --build-arg WORK_OS_API_HOST \
            --build-arg WORK_OS_CLIENT_ID \
            --build-arg SENTRY_DSN \
            --build-arg SENTRY_AUTH_TOKEN \
            -t "$DOCKER_IMAGE:$GITHUB_SHA" .
        env:
          ENVIRONMENT: ${{ github.ref_name }}
          APP_VERSION: ${{ github.sha }}
          API_URL: ${{ vars.API_URL }}
          WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          PAGE_CONTEXT_BASE_URL: ${{ vars.PAGE_CONTEXT_BASE_URL }}
          RECAPTCHA_CLIENT_KEY: ${{ vars.RECAPTCHA_CLIENT_KEY }}
          POSTHOG_API_HOST: ${{ vars.POSTHOG_API_HOST }}
          POSTHOG_KEY: ${{ vars.POSTHOG_KEY }}
          STRIPE_PUBLIC_KEY: ${{ vars.STRIPE_PUBLIC_KEY }}
          MAPBOX_TOKEN: ${{ vars.MAPBOX_TOKEN }}
          INTERCOM_APP_ID: ${{ vars.INTERCOM_APP_ID }}
          WORK_OS_API_HOST: ${{ vars.WORK_OS_API_HOST }}
          WORK_OS_CLIENT_ID: ${{ vars.WORK_OS_CLIENT_ID }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Push docker image
        run: |
          REF_NAME=${{ github.ref_name }}
          SHORT_SHA1="${GITHUB_SHA:0:7}"
          DATE=$(date +%s)

          docker tag "$DOCKER_IMAGE:$GITHUB_SHA" "$DOCKER_IMAGE:$REF_NAME-$SHORT_SHA1-$DATE"
          docker tag "$DOCKER_IMAGE:$GITHUB_SHA" "$DOCKER_IMAGE:$REF_NAME-latest"

          docker push "$DOCKER_IMAGE:$GITHUB_SHA"
          docker push "$DOCKER_IMAGE:$REF_NAME-$SHORT_SHA1-$DATE"
          docker push "$DOCKER_IMAGE:$REF_NAME-latest"
