name: Deploy

on:
  push:
    branches:
      - production
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: ${{ github.ref_name }}

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build
        env:
          VITE_ENVIRONMENT: ${{ github.ref_name }}
          VITE_APP_VERSION: ${{ github.sha }}
          VITE_AI_ASSISTANT_API_URL: ${{ vars.AI_ASSISTANT_API_URL }}
          VITE_API_URL: ${{ vars.API_URL }}
          VITE_INTERCOM_APP_ID: ${{ vars.INTERCOM_APP_ID }}
          VITE_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          VITE_PAGE_CONTEXT_BASE_URL: ${{ secrets.PAGE_CONTEXT_BASE_URL }}
          VITE_POSTHOG_API_HOST: ${{ vars.POSTHOG_API_HOST }}
          VITE_POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
          VITE_RECAPTCHA_CLIENT_KEY: ${{ secrets.RECAPTCHA_CLIENT_KEY }}
          VITE_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          VITE_WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy dist --project-name=www-koyeb-com
